### ISSUE TITLE
How to change the reference path of i18n

### ISSUE THREAD

**Issue by Leesson** [requirejs/i18n#38]
I’d like to use i18n in my project. But I met with a problem in the process. The question was that the structure of directory I designed is not fit to the requirement of i18n. This question resulted the resource files cannot be loaded normally. To be better understanding, I will include more details in the following description.
The structure of directory in my project can be abstracted as below:
```
app/  
  -- config.js  
   -- widgets/  
     -- WidgetName/  
       -- nls/  
          -- strings.js  
       -- Widget.js  
   -- index.html
```
I set up the baseUrl as the root directory of application. Then, call the resource file in the Widget.js and depends this Widget in the index.html. The code is as below:
config.js:
```js
require.config({  
    baseUrl: '/app/widgets'  
});  
```
Widget.js:
```js
define(["i18n!./nls/strings.js"], function (nls) {
    ...
});
```
index.html:
```js
require(["widgets/WidgetName/Widget"], function (Widget) {
    ...
});
```
However, when I ran the code, the request path of i18n was “app/WidgetName/nls/strings.js” other than “app/widgets/WidgetName/nls/strings.js” which I expected. It implied i18n used the directory in the index.html other than the baseUrl I set up. 

Therefore, my questions are as following:
1) How to solve this problem if I don’t want to modify the directory structure?
2) How to set up the baseUrl as the default path of i18n?

**Comment by jrburke** [comment]
The only thing that sticks out to me while scanning this issue is this dependency ID: `"i18n!./nls/strings.js"`: by specifying the ".js", that could result in [different resolution rules](http://requirejs.org/docs/api.html#jsfiles). I would just leave it off as `"i18n!./nls/strings"`.

If that does not clear up the problem, the i18n plugin wants a very specific folder structure for the nls resources, it is best to stick with how it wants to look up the files.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by Leesson** [comment]
oh, I'm so sorry for what I made such a stupid mistake. Thanks for your help
